# All NLP Core Models

In [2]:
import nltk

### Name Entity 

In [3]:
paragraph="""India (Hindi: Bhārat), officially the Republic of India (Hindi: Bhārat Gaṇarājya),[20] is a country in South Asia. It is the seventh-largest country by area, the second-most populous country, and the most populous democracy in the world. Bounded by the Indian Ocean on the south, the Arabian Sea on the southwest, and the Bay of Bengal on the southeast, it shares land borders with Pakistan to the west;[e] China, Nepal, and Bhutan to the north; and Bangladesh and Myanmar to the east. In the Indian Ocean, India is in the vicinity of Sri Lanka and the Maldives; its Andaman and Nicobar Islands share a maritime border with Thailand and Indonesia.

Modern humans arrived on the Indian subcontinent from Africa no later than 55,000 years ago."""

In [4]:
import re
paragraph=re.sub(r"\(","",paragraph)
paragraph=re.sub(r"\)","",paragraph)


In [5]:
word=nltk.word_tokenize(paragraph)

In [6]:
word_tag=nltk.pos_tag(word)

In [7]:
#word_tag
word_list_tag=[]

In [8]:
for wd in word_tag:
#    print(wd)
     word_list_tag.append(wd[0]+"_"+wd[1])

In [9]:
word_chunck=nltk.ne_chunk(word_tag)

In [10]:
type(word_chunck)

nltk.tree.Tree

In [11]:

#word_chunck.draw()


In [12]:
''' to draw inside ---------------- jupyter
import os
from IPython.display import Image, display
from nltk.draw import TreeWidget
from nltk.draw.util import CanvasFrame

def jupyter_draw_nltk_tree(tree):
    cf = CanvasFrame()
    tc = TreeWidget(cf.canvas(), tree)
    tc['node_font'] = 'arial 13 bold'
    tc['leaf_font'] = 'arial 14'
    tc['node_color'] = '#005990'
    tc['leaf_color'] = '#3F8F57'
    tc['line_color'] = '#175252'
    cf.add_widget(tc, 10, 10)
    cf.print_to_file('tmp_tree_output.ps')
    cf.destroy()
    os.system('convert tmp_tree_output.ps tmp_tree_output.png')
    display(Image(filename='tmp_tree_output.png'))
    os.system('rm tmp_tree_output.ps tmp_tree_output.png')
'''

" to draw inside ---------------- jupyter\nimport os\nfrom IPython.display import Image, display\nfrom nltk.draw import TreeWidget\nfrom nltk.draw.util import CanvasFrame\n\ndef jupyter_draw_nltk_tree(tree):\n    cf = CanvasFrame()\n    tc = TreeWidget(cf.canvas(), tree)\n    tc['node_font'] = 'arial 13 bold'\n    tc['leaf_font'] = 'arial 14'\n    tc['node_color'] = '#005990'\n    tc['leaf_color'] = '#3F8F57'\n    tc['line_color'] = '#175252'\n    cf.add_widget(tc, 10, 10)\n    cf.print_to_file('tmp_tree_output.ps')\n    cf.destroy()\n    os.system('convert tmp_tree_output.ps tmp_tree_output.png')\n    display(Image(filename='tmp_tree_output.png'))\n    os.system('rm tmp_tree_output.ps tmp_tree_output.png')\n"

In [13]:
#word_list_tag
#[word_list_tag.append(wd[0]+"_"+wd[1]) for wd in word_tag]

In [14]:
#listW=[]
#[listW.append(wd[0]+"_"+wd[1]) for wd in word_tag]

## Bag of Words


In [15]:
paragraph

'India Hindi: Bhārat, officially the Republic of India Hindi: Bhārat Gaṇarājya,[20] is a country in South Asia. It is the seventh-largest country by area, the second-most populous country, and the most populous democracy in the world. Bounded by the Indian Ocean on the south, the Arabian Sea on the southwest, and the Bay of Bengal on the southeast, it shares land borders with Pakistan to the west;[e] China, Nepal, and Bhutan to the north; and Bangladesh and Myanmar to the east. In the Indian Ocean, India is in the vicinity of Sri Lanka and the Maldives; its Andaman and Nicobar Islands share a maritime border with Thailand and Indonesia.\n\nModern humans arrived on the Indian subcontinent from Africa no later than 55,000 years ago.'

In [16]:
paragraph=paragraph+"""The world is the planet Earth and all life on it, including human civilization.[1] In a philosophical context, the "world" is the whole of the physical Universe, or an ontological world (the "world" of an individual). In a theological context, the world is the material or the profane sphere, as opposed to the celestial, spiritual, transcendent or sacred spheres. "End of the world" scenarios refer to the end of human history, often in religious contexts.

The history of the world is commonly understood as spanning the major geopolitical developments of about five millennia, from the first civilizations to the present. In terms such as world religion, world language, world government, and world war, the term world suggests an international or intercontinental scope without necessarily implying participation of every part of the world.

The world population is the sum of all human populations at any time; similarly, the world economy is the sum of the economies of all societies or countries, especially in the context of globalization. Terms such as "world championship", "gross world product", and "world flags" imply the sum or combination of all sovereign states."""

In [17]:
paragraph


'India Hindi: Bhārat, officially the Republic of India Hindi: Bhārat Gaṇarājya,[20] is a country in South Asia. It is the seventh-largest country by area, the second-most populous country, and the most populous democracy in the world. Bounded by the Indian Ocean on the south, the Arabian Sea on the southwest, and the Bay of Bengal on the southeast, it shares land borders with Pakistan to the west;[e] China, Nepal, and Bhutan to the north; and Bangladesh and Myanmar to the east. In the Indian Ocean, India is in the vicinity of Sri Lanka and the Maldives; its Andaman and Nicobar Islands share a maritime border with Thailand and Indonesia.\n\nModern humans arrived on the Indian subcontinent from Africa no later than 55,000 years ago.The world is the planet Earth and all life on it, including human civilization.[1] In a philosophical context, the "world" is the whole of the physical Universe, or an ontological world (the "world" of an individual). In a theological context, the world is the

In [18]:
import re
para_sent_token=nltk.sent_tokenize(paragraph)
for i in range(len(para_sent_token)):
    para_sent_token[i]=para_sent_token[i].lower()
    para_sent_token[i]=re.sub(r"\W"," ",para_sent_token[i])#non words to space
    para_sent_token[i]=re.sub(r"\s+"," ",para_sent_token[i])#removing extra space

In [19]:
para_sent_token

['india hindi bhārat officially the republic of india hindi bhārat gaṇarājya 20 is a country in south asia ',
 'it is the seventh largest country by area the second most populous country and the most populous democracy in the world ',
 'bounded by the indian ocean on the south the arabian sea on the southwest and the bay of bengal on the southeast it shares land borders with pakistan to the west e china nepal and bhutan to the north and bangladesh and myanmar to the east ',
 'in the indian ocean india is in the vicinity of sri lanka and the maldives its andaman and nicobar islands share a maritime border with thailand and indonesia ',
 'modern humans arrived on the indian subcontinent from africa no later than 55 000 years ago the world is the planet earth and all life on it including human civilization ',
 ' 1 in a philosophical context the world is the whole of the physical universe or an ontological world the world of an individual ',
 'in a theological context the world is the mate

#### Creating Histogram


In [20]:
word2count={}
for sent in para_sent_token:
    for word in nltk.word_tokenize(sent):
        if word in word2count.keys():
            word2count[word]+=1
        else:
            word2count[word]=1
        

In [21]:
len(word2count)

162

In [22]:
import heapq

In [23]:
word2count_100=heapq.nlargest(100,word2count,key=word2count.get)

In [24]:
type(word2count_100)

list

In [25]:
bag_of_words=[]
for sent in para_sent_token:
    temp=[]
    for word in word2count_100:
        if word in nltk.word_tokenize(sent):
            temp.append(1)
        else:
            temp.append(0)
    bag_of_words.append(temp)
            

In [26]:
#print(bag_of_words)
print(bag_of_words[0])

[1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [27]:
len(bag_of_words[0])

100

In [28]:
#making 2d array
import numpy as np

In [29]:
bag_of_words_2d=np.asarray(bag_of_words)

In [30]:
bag_of_words_2d.shape

(12, 100)

In [31]:
print(bag_of_words_2d)

[[1 0 1 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 ...
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]]


In [32]:
len(para_sent_token)

12

# TF_IDF Model 
### Term Frequency * Inverse Document Frequency 

In [33]:
paragraph

'India Hindi: Bhārat, officially the Republic of India Hindi: Bhārat Gaṇarājya,[20] is a country in South Asia. It is the seventh-largest country by area, the second-most populous country, and the most populous democracy in the world. Bounded by the Indian Ocean on the south, the Arabian Sea on the southwest, and the Bay of Bengal on the southeast, it shares land borders with Pakistan to the west;[e] China, Nepal, and Bhutan to the north; and Bangladesh and Myanmar to the east. In the Indian Ocean, India is in the vicinity of Sri Lanka and the Maldives; its Andaman and Nicobar Islands share a maritime border with Thailand and Indonesia.\n\nModern humans arrived on the Indian subcontinent from Africa no later than 55,000 years ago.The world is the planet Earth and all life on it, including human civilization.[1] In a philosophical context, the "world" is the whole of the physical Universe, or an ontological world (the "world" of an individual). In a theological context, the world is the

### Formula
tf=word occour number of times / total number of words in sentence or document

idf= log(total number of document or sentence ) /number of document or sentence cantaining the word

In [34]:
# IDF
doc_total_num=len(para_sent_token)
word2doc={}

for word in word2count_100:
    word2doc_count=0
    for sent in para_sent_token:
        if word in nltk.word_tokenize(sent):
            word2doc_count+=1
    word2doc[word]=np.log((doc_total_num/word2doc_count)+1)  

In [35]:
count=0
for key in word2doc.keys():
    print(key," ",word2doc[key])
    count+=1
    if count>15:
        break
print("\n\nOur IDF values")

the   0.6931471805599453
world   0.8472978603872034
of   0.8472978603872034
and   1.0986122886681098
is   0.9162907318741551
in   0.9162907318741551
to   1.3862943611198906
or   1.2237754316221157
on   1.9459101490553132
a   1.3862943611198906
all   1.6094379124341003
as   1.3862943611198906
india   1.9459101490553132
country   1.9459101490553132
it   1.6094379124341003
indian   1.6094379124341003


Our IDF values


In [36]:
# TF 

tf_words={}
for word in word2count_100:
    temp=[]
    for sent in para_sent_token:
        word_counter=0
        for w in nltk.word_tokenize(sent):
            if w==word:
                word_counter+=1
        tf=word_counter/len(nltk.word_tokenize(sent))
        temp.append(tf)    
    tf_words[word]=temp
    
            
        

In [37]:
#print(tf_words)

In [38]:
len(tf_words)

100

### TFIDF Model

In [39]:
tfidf_matrix=[]
for word in tf_words.keys():
    tf_idf=[]
    for val in tf_words[word]:
        score=val*word2doc[word]
        tf_idf.append(score)
    tfidf_matrix.append(tf_idf)
        

In [40]:
#word2doc

In [ ]:
tfidf_model["the"]

In [ ]:
for k,value in tf_words.items():
    print(k,value)
    break

In [ ]:
para_sent_token[0]

In [ ]:
#tf_words

In [ ]:
x=np.asarray(tfidf_matrix)
print(x.shape)
x

In [ ]:
x[0]

In [ ]:
y=np.transpose(x)
print(y.shape)
y

In [ ]:
who

### other models in part 2 file